### ISSUE TITLE
Fix .travis.yml deploy instructions

### ISSUE THREAD

**Issue by barraponto** [GlutexaTF/integrationtest#1]
Hi Kim, I noticed your `.travis.yml` file is missing some fields. Probably due to running `travis encrypt YOURKEY --add deploy.key`. Notice how that command just adds the `deploy.key` info to the file? Running the `travis setup heroku` would have written the whole file!

I know it's not working on your machine, that's why we ended up using `travis encrypt` in the first place. But the other fields are easy to fill in manually. Here's a sample `.travis.yml` file for you to mimic:

```yml
deploy:
  provider: heroku
  api_key:
    secure: X3YhS0OeHG/Kco2alG11oqiQQ/n6INTw2SRNDqxVkeBf8EE8JXu1Hzdo9xBR/epUdmm2O8mSkTLWJkDE/3uljRGe2kQGYrcJmLGvckaCVHFWy1M6xLhb8j1IbsK5iJwoZdFtayZYmHtSoI3ry+Q3gbMNgtsL9S8a9HLxBAUhfWmA8h/Kq+kC66mp6+2xelx2Iel9TEi6ogi7Wns/85mJM7IPYBUKm2v+naPgGnzXzBMRVmCgYHA/5UrtEB55qUnDW1TYQq4rbqCP/HZ+4mropPjSf6GzvBR6EL1k5g6mAnXzE3jG8MYca/XPYykPjxpCr6Kq8o+maZb1ywX45KZsc+bMCzMX/nfLDHJTCujOqDG2uNfFE6Ml+67jCy/k2FL2dtnByGyEKJxW1P037eNi05ehU+OuH7CTNw312U6+728VI0BN/9NqZaWp3GF6IhNr4LHBb6S8KBDpUJuqyk2ZmVpYdWv0udhbPFrJD1WpOf33rx4TFThqQL0sbw1scz+t7S/J1NSA1s2v2NXH7Fxq68fVQ1tauG+W+wWYapLRkLkrrvOmo/mthEln6891Xqt4y3qdJOwr1/uqvu6lsJkEnwGpCmW2kMPpteWDf303j4flXeSlSQf5KCiZZEKk05VXlRu+pavih7avFVzrd+sRi7Z/Q9ACHXKL4QJ3A84Smo8=
  app: tf-heroku-travis
  on:
    repo: barraponto/tf-heroku-travis
```
